### ISSUE TITLE
Item Prices

### ISSUE THREAD

**Issue by PhilMasters** [Firedrake/discworld-rpg#3]
Item prices need to be in Ankh-Morpork dollars (equal to 20 GURPS dollars). Note that one or two had already been changed before the project started.

**Comment by Firedrake** [comment]
And presumably wealth levels?

**Comment by PhilMasters** [comment]
I believe that those have already been set correctly in the starting file.

Incidentally, there won't be much harm in leaving in TL 0-4 items from the Basic Set that don't happen to be mentioned in the Discworld book, provided that the prices are adjusted. But there are some brand new items that will need adding.

**Comment by PhilMasters** [comment]
Resolved by latest commit.
