### ISSUE TITLE
Spells

### ISSUE THREAD

**Issue by PhilMasters** [Firedrake/discworld-rpg#6]
Discworld doesn't have "spells" in the Basic Set sense; what it has are essentially what the Basic Set calls Techniques for the various Magical Form skills. It'd be nice to either delete/suppress the Spells tab, if that's possible, or even better have those Techniques appear in that tab.

**Comment by Firedrake** [comment]
I've just removed all the actual named spells, which is a start. (Also fixes some invalid UTF-8.)

**Comment by PhilMasters** [comment]
I've now dealt with a lot of this, but multi-Form spells still need to be sorted out.
